### ISSUE TITLE
resolve_links_in_str renvoie une exception non gérée si le lien pointe sur un type != string

### ISSUE THREAD

**Issue by RiwsPy** [RiwsPy/yaml-DB-patcher#1]
Exemple :

```
source:
  hp: 12

to:
  hp: << source.hp >>
```
Une solution serait de changer l'approche, plutôt que traiter le fichier comme une string géante.
La convertir en dictionnaire puis de convertir tous les liens dans les values().

**Comment by RiwsPy** [comment]
Afin de converser le type des données, la résolution des liens se fait désormais sur toutes les values() de la db.
```
person:
  hp: 1

other_person:
  hp: <<person.hp>>
```
Devient
```
{
 "person": {
  "hp": 1
 },
 "other_person": {
  "hp": 1
 }
}
```
