### ISSUE TITLE
Fix: appel récursif lorsque le fix a besoin de la valeur d'origine

### ISSUE THREAD

**Issue by RiwsPy** [RiwsPy/yaml-DB-patcher#10]
```
$example:
  value: 2

F£.$example:
  value: <<$example.value>>
```

Il peut être pratique de le faire lorsque l'on veut monter une valeur au carré :
```
value|*: <<$example.value>>
```
