### ISSUE TITLE
Un fix n'est pas pris en compte lorsqu'il est présent avant l'entrée concernée

### ISSUE THREAD

**Issue by RiwsPy** [RiwsPy/yaml-DB-patcher#2]
```
F£.man.res.fire|+: 1
man:
    res:
        ice: 1
        fire: 2
```
Devient
```
man:
  res:
    fire: 2
    ice: 1
```
