### ISSUE TITLE
Liens imbriqués non fonctionnels

### ISSUE THREAD

**Issue by RiwsPy** [RiwsPy/yaml-DB-patcher#6]
```
person:
  name: Loulou

other:
  hp: << << person.name >>.hp >>

Loulou:
  hp: 2
```
Devient
```
Loulou:
  hp: 2
other:
  hp: << Loulou.hp >>
person:
  name: Loulou
```

**Comment by RiwsPy** [comment]
```
person:
  name: Loulou

other:
  hp: << << person.name >>.hp >>

Loulou:
  hp: 2
```
Devient désormais
```
Loulou:
  hp: 2
other:
  hp: 2
person:
  name: Loulou
```
